# Generated by Django 2.2.3 on 2021-04-08 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 13, 0, 26, 671269)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 13, 0, 26, 671244)),
        ),
    ]
